services:
  postgresql:
    image: postgres:14.15-alpine3.21
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}Pg123
      POSTGRES_USER: ${POSTGRES_USER}kubenews
      POSTGRES_DB: ${POSTGRES_DB}kubenews
    volumes:
      - postgre_vol:/var/lib/postgresql/data
    networks:
      - kubenews_net
  
  kube_news:
    image: gabrieloliver001/kube-news-docker:${IMAGE_TAG:-latest}
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - kubenews_net
    depends_on:
      - postgresql
    environment:
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_USERNAME: ${POSTGRES_USER}
      DB_DATABASE: ${POSTGRES_DB}
      DB_HOST: postgresql


volumes:
  postgre_vol:
    name: postgre_vol

networks:
  kubenews_net:
    driver: bridge